"""Generic content data models for web scraping."""

from datetime import datetime
from pathlib import Path
from typing import List

from pydantic import BaseModel, Field


class ContentSection(BaseModel):
    """A section of content with title and content."""

    title: str = ""
    content: str = ""


class ContentData(BaseModel):
    """Generic schema for scraped content data."""

    title: str = ""
    category: str = ""
    summary: str = ""
    sections: List[ContentSection] = Field(default_factory=list)
    source_url: str = ""
    scraped_at: datetime = Field(default_factory=datetime.utcnow)

    def to_json_file(self, path: Path) -> None:
        """Save to JSON file with ISO-8601 datetime formatting.

        Args:
            path: File path to save JSON
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.model_dump_json(indent=2))

    @classmethod
    def from_json_file(cls, path: Path) -> "ContentData":
        """Load from JSON file.

        Args:
            path: File path to load from

        Returns:
            ContentData instance
        """
        with open(path, "r", encoding="utf-8") as f:
            return cls.model_validate_json(f.read())


class EnrichedContentSection(ContentSection):
    """Content section with LLM-classified section type.

    This extends ContentSection with a section_type field that is
    populated by the LLM enrichment layer.
    """

    section_type: str = "other"  # From canonical enum


class EnrichedContentData(ContentData):
    """Enriched content data with LLM-classified sections.

    This is generated by the LLM post-processor and should
    never be used as the ground truth.
    """

    sections: List[EnrichedContentSection] = Field(default_factory=list)


# Generic canonical section types (can be customized per use case)
CANONICAL_SECTION_TYPES = [
    "overview",
    "requirements",
    "eligibility",
    "cost",
    "fees",
    "duration",
    "timeline",
    "process",
    "how_to_apply",
    "documents",
    "benefits",
    "conditions",
    "restrictions",
    "related_info",
    "other",
]
