"""Visa data models - Locked schema as per plan.md."""

from datetime import datetime
from pathlib import Path
from typing import List

from pydantic import BaseModel, Field


class VisaSection(BaseModel):
    """A section of visa information with title and content."""

    title: str = ""
    content: str = ""


class VisaData(BaseModel):
    """Locked schema for visa data - ground truth from scraping.

    This schema is strictly enforced and must not be modified.
    """

    visa_name: str = ""
    subclass: str = ""
    category: str = ""
    summary: str = ""
    sections: List[VisaSection] = Field(default_factory=list)
    source_url: str = ""
    scraped_at: datetime = Field(default_factory=datetime.utcnow)

    def to_json_file(self, path: Path) -> None:
        """Save to JSON file with ISO-8601 datetime formatting.

        Args:
            path: File path to save JSON
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.model_dump_json(indent=2))

    @classmethod
    def from_json_file(cls, path: Path) -> "VisaData":
        """Load from JSON file.

        Args:
            path: File path to load from

        Returns:
            VisaData instance
        """
        with open(path, "r", encoding="utf-8") as f:
            return cls.model_validate_json(f.read())


class EnrichedVisaSection(VisaSection):
    """Visa section with LLM-classified section type.

    This extends VisaSection with a section_type field that is
    populated by the LLM enrichment layer.
    """

    section_type: str = "other"  # From canonical enum


class EnrichedVisaData(VisaData):
    """Enriched visa data with LLM-classified sections.

    This is generated by the LLM post-processor and should
    never be used as the ground truth.
    """

    sections: List[EnrichedVisaSection] = Field(default_factory=list)


# Canonical section types enum (locked)
CANONICAL_SECTION_TYPES = [
    "overview",
    "eligibility",
    "cost",
    "processing_time",
    "duration",
    "work_rights",
    "study_rights",
    "conditions",
    "family",
    "how_to_apply",
    "documents",
    "other",
]
